# Generated by Django 5.2.4 on 2026-07-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("environment", "0020_climateanalysisresult_processing_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remotesensingimage",
            name="acquisition_date",
            field=models.DateField(blank=True, null=True, verbose_name="获取日期"),
        ),
        migrations.AlterField(
            model_name="remotesensingimage",
            name="center_lat",
            field=models.FloatField(blank=True, null=True, verbose_name="中心纬度"),
        ),
        migrations.AlterField(
            model_name="remotesensingimage",
            name="center_lon",
            field=models.FloatField(blank=True, null=True, verbose_name="中心经度"),
        ),
    ]
